# Generated by Django 5.0.14 on 2026-05-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardew', '0002_alter_farmingitem_id_alter_fishingitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(choices=[('crafts_room', 'Crafts Room'), ('pantry', 'Pantry'), ('fish_tank', 'Fish Tank'), ('boiler_room', 'Boiler Room'), ('bulletin_board', 'Bulletin Board'), ('vault', 'Vault')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(default=1)),
                ('donated', models.BooleanField(default=False)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='stardew.bundle')),
                ('farming_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stardew.farmingitem')),
                ('fishing_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stardew.fishingitem')),
                ('foraging_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stardew.foragingitem')),
            ],
        ),
    ]
